root: true
parser: "@typescript-eslint/parser"
plugins: ["@typescript-eslint"]
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-unused-vars":
    - warn
    - { varsIgnorePattern: "_", argsIgnorePattern: "_" }
  padding-line-between-statements:
    - warn
    - { blankLine: always, prev: export, next: export }
    - { blankLine: always, prev: function, next: export }
    - { blankLine: always, prev: function, next: function }
  prefer-const: off
