export const TRIBES = [
  "Adasier",
  "Cirefalier",
  "Fedaki",
  "Genver",
  "Jahann",
  "Jargier",
  "Kamorian",
  "Marnakh-tirak",
  "Missla",
  "Pyar",
  "Taup",
  "Zolod",
]

export const ARCHETYPES = [
  "Donare",
  "Krigare",
  "Ledare",
  "Lärd",
  "Mystiker",
  "Skugga",
  "Underhållare",
]

export const ENVIRONMENT = [
  "Hav",
  "Hovliv",
  "Landsbygd",
  "Lärosäte",
  "Stad",
  "Undre värld",
  "Vildmark",
]

export const ATTRIBUTES = [
  "Styrka",
  "Tålighet",
  "Rörlighet",
  "Uppfattning",
  "Psyke",
  "Vilja",
  "Utstrålning",
]

export const ATTRIBUTES_SECONDARY = [
  "Förflyttning",
  "Intryck",
  "Kroppsbyggnad",
  "Reaktion",
  "Självkontroll",
  "Vaksamhet",
  "Grundskada",
  "Livskraft",
]

export const TABLE_GROUPS = [
  { name: "Färder & äventyr" },
  { name: "Intriger & illgärningar" },
  { name: "Kunskap & mysterier" },
  { name: "Strider & drabbningar" },
  { name: "Valfri händelsetabell" },
]

export const SKILL_GROUPS = [
  { name: "Valfria färdigheter" },
  { name: "Kunskapsfärdigheter" },
  { name: "Mystikfärdigheter" },
  { name: "Rörelsefärdigheter" },
  { name: "Sociala färdigheter" },
  { name: "Stridsfärdigheter" },
  { name: "Vildmarksfärdigheter" },
  { name: "Expertiser" },
  { name: "Hantverk" },
  { name: "Kännetecken" },
  { name: "Mysterier" },
  { name: "Språkenheter" },
]

export const SKILL_LIST = [
  "Argumentera",
  "Armborst",
  "Berättarkonst",
  "Båge",
  "Ceremoni",
  "Charm",
  "Dansa",
  "Dolk",
  "Dupera",
  "Filosofi",
  "Fingerfärdighet",
  "Förnimma",
  "Förvränga",
  "Genomskåda",
  "Genomsöka",
  "Geografi",
  "Gifter & Droger",
  "Gömma",
  "Handel",
  "Historia",
  "Hoppa",
  "Hovliv",
  "Injaga fruktan",
  "Jakt & fiske",
  "Kanalisera",
  "Kastvapen",
  "Kedjevapen",
  "Klubba",
  "Klättra",
  "Krigföring",
  "Kulturkännedom",
  "Köra vagn",
  "Lagkunskap",
  "Ledarskap",
  "Läkekonst",
  "Låsdyrkning",
  "Marsch",
  "Naturlära",
  "Navigation",
  "Ockultism",
  "Orientering",
  "Rida",
  "Simma",
  "Sjömannaskap",
  "Skumraskaffärer",
  "Sköld",
  "Slagsmål",
  "Smyga",
  "Speja",
  "Spel & dobbel",
  "Spjut",
  "Spåra",
  "Stav",
  "Svärd",
  "Sång & musik",
  "Teologi",
  "Teoretisk magi",
  "Undervisa",
  "Undvika",
  "Vildmarksvana",
  "Yxa",
]
